name: WebDriver Test Automation

on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main, develop ]
  workflow_dispatch:
env:
  JAVA_VERSION: '25'
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: 📦 Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
            
      - name: 🌐 Setup Chrome
        if: matrix.browser == 'chrome'
        uses: nanasess/setup-chromedriver@v2

      - name: 🌐 Verify Chrome Installation
        if: matrix.browser == 'chrome'
        run: |
          google-chrome --version
          which google-chrome

      - name: 🌐 Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@latest

      - name: 🌐 Verify Firefox Installation
        if: matrix.browser == 'firefox'
        run: |
          firefox --version
          which firefox




      - name: Run Tests
        run: mvn clean test -Dbrowser=${{ matrix.browser }} -Dmode=headless  -Dsurefire.reportFormat=xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: |
            target/surefire-reports/
            target/extent-reports/
            target/screenshots/

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'target/surefire-reports/*.xml'
          check_name: 'Test Results (${{ matrix.browser }})'
